{% set name = "ploomber-engine" %}
{% set version = "0.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-engine-{{ version }}.tar.gz
  sha256: 346ad30f85749106766fc1a0c366fe6bb08afdbd0a5ed30612f5322a63eaf03f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ploomber-core >=0.0.11
    - debuglater
    - nbclient
    - ipython
    - parso
    - nbformat
    - click

test:
  imports:
    - ploomber_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-engine/
  summary: 'A toolbox for Jupyter notebooks: testing, experiment tracking, debugging, profiling, and more!'
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
