{% set name = "ploomber-engine" %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-engine-{{ version }}.tar.gz
  sha256: fd4e68ca9aa9303e89465b57418a193634512b20b402a494ab3a65809a1fceee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ploomber-core >=0.2
    - debuglater >=1.4.4
    - nbclient
    - ipython
    - parso
    - nbformat
    - click
    - tqdm

test:
  imports:
    - ploomber_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-engine/
  summary: 'A toolbox for Jupyter notebooks: testing, experiment tracking, debugging, profiling, and more!'
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
