{% set name = "ploomber-engine" %}
{% set version = "0.0.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-engine-{{ version }}.tar.gz
  sha256: 78f9e9d12db5571a716038359443a90009b57af757c25d84613bfd1920cfd07d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ploomber-core >=0.0.11
    - debuglater
    - nbclient
    - ipython
    - parso
    - nbformat
    - click
    - tqdm

test:
  imports:
    - ploomber_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-engine/
  summary: 'A toolbox for Jupyter notebooks: testing, experiment tracking, debugging, profiling, and more!'
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
