{% set name = "ploomber-engine" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-engine-{{ version }}.tar.gz
  sha256: 24a557b94ed226af86017267c74062f01854653d5f9a341b488e136ff700a80b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ploomber-core >=0.0.4
    - papermill
    - ipykernel
    - debuglater
    - nbclient
    - ipython
    - parso
    - nbformat

test:
  imports:
    - ploomber_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-engine/
  summary: Add debugging and profiling capabilities to papermill.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
