{% set name = "ploomber-engine" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ploomber-engine-{{ version }}.tar.gz
  sha256: b053004fc24283121d76d77d1fb43872d1fc224837d10c176c98b18aa124a778

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - ploomber-core >=0.0.11
    - debuglater
    - nbclient
    - ipython
    - parso
    - nbformat
    - click

test:
  imports:
    - ploomber_engine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/ploomber-engine/
  summary: "A toolbox for Jupyter notebooks: testing, experiment tracking, debugging, profiling, and more!"
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - edublancas
